version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    command: /venv/bin/python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src/:/code/
