version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0 127.0.0.1 localhost
      - PYTHONUNBUFFERED=1
      - ALLOWED_IPS=172.19.0.1
    command: /venv/bin/python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src/:/code/
