# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('balance', models.FloatField()),
                ('currency', models.CharField(choices=[(b'EURO', b'EUR'), (b'POUND', b'GBP')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('weboob_module', models.CharField(choices=[(b'citelis', 'Cit\xe9lis'), (b'spirica', 'Spirica'), (b'creditmutuel', 'Cr\xe9dit Mutuel'), (b'cmmc', 'Cr\xe9dit Mutuel Massif Central'), (b'afer', 'afer website'), (b'societegenerale', 'Soci\xe9t\xe9 G\xe9n\xe9rale'), (b'cmes', 'Cr\xe9dit Mutuel \xc9pargne Salariale'), (b'fortuneo', 'Fortuneo'), (b'bnppere', 'BNP \xc9pargne Salariale'), (b'apivie', 'Apivie'), (b'barclays', 'Barclays'), (b'kiwibank', 'Kiwibank'), (b'yomoni', 'Yomoni'), (b'amundi', 'amundi website'), (b'btpbanque', 'BTP Banque'), (b'creditdunordpee', 'Site de gestion du PEE du groupe Credit du nord'), (b'ing', 'ING Direct'), (b'delubac', 'Banque Delubac & Cie'), (b'banqueaccord', 'Banque Accord'), (b'axabanque', 'AXA Banque'), (b'americanexpress', 'American Express'), (b'pradoepargne', 'Prado \xc9pargne Salariale'), (b'caels', 'Cr\xe9dit Agricole - Epargne Longue des Salari\xe9s'), (b'carrefourbanque', 'Carrefour Banque'), (b'bforbank', 'BforBank'), (b'n26', 'Bank N26'), (b'groupamaes', 'Groupama \xc9pargne Salariale'), (b'cragr', 'Cr\xe9dit Agricole'), (b'bnporc', 'BNP Paribas'), (b'linebourse', 'linebourse website'), (b'banquepopulaire', 'Banque Populaire'), (b'caissedepargne', "Caisse d'\xc9pargne"), (b'paypal', 'PayPal'), (b'amazonstorecard', 'Amazon Store Card'), (b'erehsbc', 'HSBC \xc9pargne Salariale'), (b'creditdunord', 'Cr\xe9dit du Nord, Banque Courtois, Kolb, Nuger, Laydernier, Tarneaud, Soci\xe9t\xe9 Marseillaise de Cr\xe9dit'), (b'cices', 'CIC \xc9pargne Salariale'), (b'bp', 'La Banque Postale'), (b'cmso', 'Cr\xe9dit Mutuel Sud-Ouest'), (b'oney', 'Oney'), (b'lcl', 'LCL'), (b'capeasi', 'AXA \xc9pargne Salariale'), (b'creditcooperatif', 'Cr\xe9dit Coop\xe9ratif'), (b'cic', 'CIC'), (b'wellsfargo', 'Wells Fargo'), (b'ganassurances', 'Groupama'), (b'citibank', 'Citibank'), (b's2e', '\xc9pargne Salariale'), (b'cmb', 'Credit Mutuel de Bretagne'), (b'hsbc', 'HSBC France'), (b'bred', 'Bred'), (b'vicseccard', "Victoria's Secret Angel Card"), (b'alloresto', 'Allo Resto'), (b'esalia', 'Soci\xe9t\xe9 G\xe9n\xe9rale \xc9pargne Salariale'), (b'boursorama', 'Boursorama')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gringotts.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gringotts.Category')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gringotts.Bank'),
        ),
    ]
